substitutions:
  _COMMIT_SHA: 'latest'

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/promising-era-448623-i8/mohit100966813/app:$_COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/promising-era-448623-i8/mohit100966813/app:$_COMMIT_SHA']

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app02' # Change to your Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/promising-era-448623-i8/mohit100966813/app:$_COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
